/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfase;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import operaciones.clsFuncionario;

/**
 *
 * @author Usuario
 */
public class iCorregir extends javax.swing.JFrame {
    private DefaultTableModel model;
    ArrayList misBorrados = new ArrayList();
    JPanelPresencia panel;
    int filaDeLaTabla = 0;
     /**    

     * Creates new form iCorregir
     */
    public iCorregir() {
        initComponents();
    }

    iCorregir(ArrayList borrados, JPanelPresencia presencia) {
        initComponents();
        misBorrados = borrados;
        this.panel = presencia;
        carguemosTabla();   
        misBorrados.removeAll(misBorrados);
        
     ///throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void carguemosTabla(){
        int i = 0;
        String[] titulos = {"Chapa", "Nombre", "Apellido"}; 
              model = new DefaultTableModel(null, titulos){
                  @Override
                  public boolean isCellEditable(int row, int column) {
                   //all cells false
                  return false;
                  }
              };
              String[] filas = new String[3];
              for (i=0; i< misBorrados.size(); i++){
                    filas = (String[]) misBorrados.get(i);
                    model.addRow(filas);
              }
            this.jTablaCorreccion.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCorreccion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Corregir Presencia");
        setAlwaysOnTop(true);

        jTablaCorreccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Chapa", "Nombre", "Apellido"
            }
        ));
        jTablaCorreccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaCorreccionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaCorreccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jTablaCorreccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaCorreccionMouseClicked
        String[] DatosDeBorrados = new String[3];
        
            if (evt.getClickCount() == 2 && !evt.isConsumed()){
            this.filaDeLaTabla = jTablaCorreccion.getSelectedRow();
            
            DatosDeBorrados[0] = (String) model.getValueAt(filaDeLaTabla, 0);
            DatosDeBorrados[1] = (String) model.getValueAt(filaDeLaTabla, 1);
            DatosDeBorrados[2] = (String) model.getValueAt(filaDeLaTabla, 2);
            
           
            panel.rellenarTabla(DatosDeBorrados);
            model.removeRow(filaDeLaTabla);
            
            
        }
    }//GEN-LAST:event_jTablaCorreccionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iCorregir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iCorregir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iCorregir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iCorregir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new iCorregir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTablaCorreccion;
    // End of variables declaration//GEN-END:variables

}
