/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfase;

import javax.swing.ButtonGroup;

/**
 *
 * @author Usuario
 */
public class Justificaciones extends javax.swing.JFrame {
    String causas="";
    String ju="";
    /**
     * Creates new form Justificaciones
     */
    public Justificaciones() {
        initComponents();
        groupButton();
        jComboJustificaciones.setEnabled(false);
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboMotivos = new javax.swing.JComboBox();
        jRadioConAviso = new javax.swing.JRadioButton();
        jRadioSinAviso = new javax.swing.JRadioButton();
        jRadioDocumentacionSi = new javax.swing.JRadioButton();
        jRadioDocuemtacionNo = new javax.swing.JRadioButton();
        jComboJustificaciones = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Justificacion de Falta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Motivo");

        jComboMotivos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboMotivos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Falta", "Franco", "Licencia Anual", "Enfermedad", "Seguro de Paro" }));
        jComboMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMotivosActionPerformed(evt);
            }
        });

        jRadioConAviso.setText("Con Aviso");

        jRadioSinAviso.setText("Sin Aviso");

        jRadioDocumentacionSi.setText("Anexa Documentacion");
        jRadioDocumentacionSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDocumentacionSiActionPerformed(evt);
            }
        });

        jRadioDocuemtacionNo.setText("No Anexa Documentacion");
        jRadioDocuemtacionNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDocuemtacionNoActionPerformed(evt);
            }
        });

        jComboJustificaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboJustificaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paternidad", "Medica", "Fallecimiento", "Citacion Judicial", "Donacion de Sangre", "Sindical", "Estudios", "Otro" }));
        jComboJustificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboJustificacionesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Justificación:");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboJustificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioConAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioSinAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioDocumentacionSi)
                            .addComponent(jRadioDocuemtacionNo))
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioConAviso)
                    .addComponent(jRadioDocumentacionSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioSinAviso)
                    .addComponent(jRadioDocuemtacionNo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboJustificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMotivosActionPerformed
        if (jComboMotivos.getSelectedIndex()==0){
            enableButtons();
        }else
            disableButtons();
    }//GEN-LAST:event_jComboMotivosActionPerformed

    private void jRadioDocumentacionSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDocumentacionSiActionPerformed
        if (jRadioDocumentacionSi.isSelected()){
            jComboJustificaciones.setEnabled(true);
        }
        
    }//GEN-LAST:event_jRadioDocumentacionSiActionPerformed

    private void jRadioDocuemtacionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDocuemtacionNoActionPerformed
        if(jRadioDocuemtacionNo.isSelected()){
            jComboJustificaciones.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioDocuemtacionNoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        jPanelInconsistencia inco= new jPanelInconsistencia();
        String ca="", ad="";
        if (jRadioConAviso.isSelected()){
            ca = "con aviso";
            if (jRadioDocumentacionSi.isSelected()){
                ad = "anexa";
            }
        }
        
              
        causas = jComboMotivos.getSelectedItem() +" "+ ca + " " + ad + " " + ju;
        causas.trim();
        inco.justificacion = causas;
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboJustificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboJustificacionesActionPerformed
        ju =(String) jComboJustificaciones.getSelectedItem();
    }//GEN-LAST:event_jComboJustificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Justificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Justificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Justificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Justificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Justificaciones().setVisible(true);
            }
        });
    }
    public void disableButtons(){
        jRadioConAviso.setEnabled(false);
        jRadioSinAviso.setEnabled(false);
        jRadioDocumentacionSi.setEnabled(false);
        jRadioDocuemtacionNo.setEnabled(false);
    
    }
    
    public void enableButtons(){
    jRadioConAviso.setEnabled(true);
            jRadioSinAviso.setEnabled(true);
            jRadioDocumentacionSi.setEnabled(true);
            jRadioDocuemtacionNo.setEnabled(true);
    
    }
    
    
    private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );
ButtonGroup bg2 = new ButtonGroup( );

bg1.add(jRadioConAviso);
bg1.add(jRadioSinAviso);

   disableButtons();

bg2.add(jRadioDocumentacionSi);
bg2.add(jRadioDocuemtacionNo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboJustificaciones;
    private javax.swing.JComboBox jComboMotivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioConAviso;
    private javax.swing.JRadioButton jRadioDocuemtacionNo;
    private javax.swing.JRadioButton jRadioDocumentacionSi;
    private javax.swing.JRadioButton jRadioSinAviso;
    // End of variables declaration//GEN-END:variables
}
